name: Deploy To S3 And Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치하기
        run: npm i

      - name: build 하기
        run: npm run build

      - name: AWS Resource에 접근할 수 있게 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: S3 기존 파일들 전체 삭제 및 새로운 빌드 파일 업로드
        run: |
          aws s3 rm --recursive s3://practice-cloudfront-01
          aws s3 cp ./dist s3://practice-cloudfront-01/ --recursive
